[package]
authors = ["sepiropht"]
categories = ["wasm"]
description = "Toy project to learn wasm and rust!"
license = "Apache-2.0/MIT"
name = "tic-tac-toe-wasm"
readme = "./README.md"
repository = "https://github.com/sepiropht/tic-tac-toe-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "0.1.5"
wasm-bindgen = "0.2.25"
js-sys = "0.3"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.5", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.2", optional = true }

[dependencies.web-sys]
version = "0.3.10"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
  "console",
]

[features]
default = ["console_error_panic_hook"]
